#pragma once

#include <string_view>

enum class /*[[nodiscard]]*/ Card : short {
  none = 0,
  twoSpade = 1,
  threeSpade = 2,
  fourSpade = 3,
  fiveSpade = 4,
  sixSpade = 5,
  sevenSpade = 6,
  eightSpade = 7,
  nineSpade = 8,
  tenSpade = 9,
  jackSpade = 10,
  queenSpade = 11,
  kingSpade = 12,
  aceSpade = 13,
  twoHeart = 14,
  threeHeart = 15,
  fourHeart = 16,
  fiveHeart = 17,
  sixHeart = 18,
  sevenHeart = 19,
  eightHeart = 20,
  nineHeart = 21,
  tenHeart = 22,
  jackHeart = 23,
  queenHeart = 24,
  kingHeart = 25,
  aceHeart = 26,
  twoDiamond = 27,
  threeDiamond = 28,
  fourDiamond = 29,
  fiveDiamond = 30,
  sixDiamond = 31,
  sevenDiamond = 32,
  eightDiamond = 33,
  nineDiamond = 34,
  tenDiamond = 35,
  jackDiamond = 36,
  queenDiamond = 37,
  kingDiamond = 38,
  aceDiamond = 39,
  twoClub = 40,
  threeClub = 41,
  fourClub = 42,
  fiveClub = 43,
  sixClub = 44,
  sevenClub = 45,
  eightClub = 46,
  nineClub = 47,
  tenClub = 48,
  jackClub = 49,
  queenClub = 50,
  kingClub = 51,
  aceClub = 52
};

[[nodiscard]] std::string_view toString(Card c);
[[nodiscard]] Card toCard(std::string_view card);